DROP TABLE IF EXISTS movie_actors;
DROP TABLE IF EXISTS actor;
DROP TABLE IF EXISTS movie;
DROP TABLE IF EXISTS "User";

CREATE TABLE actor
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_actor PRIMARY KEY (id)
);

CREATE TABLE movie
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title    VARCHAR(255),
    director VARCHAR(255),
    "year"     INT NOT NULL,
    CONSTRAINT pk_movie PRIMARY KEY (id)
);

CREATE TABLE movie_actors
(
    actor_id BIGINT NOT NULL,
    movie_id BIGINT NOT NULL,
    CONSTRAINT pk_movie_actors PRIMARY KEY (actor_id, movie_id)
);

ALTER TABLE movie_actors
    ADD CONSTRAINT fk_movact_on_actor FOREIGN KEY (actor_id) REFERENCES actor (id) ON DELETE CASCADE;

ALTER TABLE movie_actors
    ADD CONSTRAINT fk_movact_on_movie FOREIGN KEY (movie_id) REFERENCES movie (id) ON DELETE CASCADE;

CREATE TABLE "User"
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email_address   VARCHAR(255)                            NOT NULL,
    hashed_password VARCHAR(255)                            NOT NULL,
    role            VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id)
);

ALTER TABLE "User"
    ADD CONSTRAINT uc_user_emailaddress UNIQUE (email_address);
